name: actn4-md-analysis
channels:
  - conda-forge
dependencies:
  - python=3.13
  - numpy=2.4
  - pandas=3.0
  - matplotlib=3.10
  - scipy=1.17
  - mdtraj=1.11
  - mrcfile=1.5
  - jax=0.9
  - jaxlib=0.9
  - equinox=0.13
  - ipykernel=7.2
  - notebook
  - pip
  - pip:
      - cryojax==0.5.5
